// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: nxin.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nxin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Telphone string `protobuf:"bytes,3,opt,name=Telphone,proto3" json:"Telphone,omitempty"`
}

func (x *Nxin) Reset() {
	*x = Nxin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nxin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nxin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nxin) ProtoMessage() {}

func (x *Nxin) ProtoReflect() protoreflect.Message {
	mi := &file_nxin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nxin.ProtoReflect.Descriptor instead.
func (*Nxin) Descriptor() ([]byte, []int) {
	return file_nxin_proto_rawDescGZIP(), []int{0}
}

func (x *Nxin) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Nxin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nxin) GetTelphone() string {
	if x != nil {
		return x.Telphone
	}
	return ""
}

var File_nxin_proto protoreflect.FileDescriptor

var file_nxin_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x78, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x46, 0x0a, 0x04, 0x4e, 0x78, 0x69, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x65, 0x6c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x05,
	0x5a, 0x03, 0x2e, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nxin_proto_rawDescOnce sync.Once
	file_nxin_proto_rawDescData = file_nxin_proto_rawDesc
)

func file_nxin_proto_rawDescGZIP() []byte {
	file_nxin_proto_rawDescOnce.Do(func() {
		file_nxin_proto_rawDescData = protoimpl.X.CompressGZIP(file_nxin_proto_rawDescData)
	})
	return file_nxin_proto_rawDescData
}

var file_nxin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nxin_proto_goTypes = []interface{}{
	(*Nxin)(nil), // 0: protobuf.Nxin
}
var file_nxin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nxin_proto_init() }
func file_nxin_proto_init() {
	if File_nxin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nxin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nxin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nxin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nxin_proto_goTypes,
		DependencyIndexes: file_nxin_proto_depIdxs,
		MessageInfos:      file_nxin_proto_msgTypes,
	}.Build()
	File_nxin_proto = out.File
	file_nxin_proto_rawDesc = nil
	file_nxin_proto_goTypes = nil
	file_nxin_proto_depIdxs = nil
}
